### ISSUE TITLE
Twitter push returns an error in output log.

### ISSUE THREAD

**Issue by meteorkees** [jekhokie/raspberry-noaa-v2#541]
**Describe the bug**
After setting the flag to true to push the images to Twitter I got the error in return. See log output:
Any thoughts or suggestions?

**Screenshots and/or logs**
03-06-2022 10:25 /home/pi/raspberry-noaa-v2/scripts/receive_noaa.sh INFO : Pushing image enhancements to Twitter
03-06-2022 10:25 /home/pi/raspberry-noaa-v2/scripts/push_processors/push_twitter.sh INFO : Posting images to Twitter feed:
03-06-2022 10:25 /home/pi/raspberry-noaa-v2/scripts/push_processors/push_twitter.sh INFO :    /srv/images/NOAA-18-20220603-095815-MCIR.jpg /srv/images/NOAA-18-20220603-095815-MCIR-precip.jpg /srv/images/NOAA-18-20220603-095815-MSA.jpg /srv/images/NOAA-18-20220603-095815-MSA-precip.jpg /srv/images/NOAA-18-20220603-095815-HVC-precip.jpg /srv/images/NOAA-18-20220603-095815-HVCT-precip.jpg /srv/images/NOAA-18-20220603-095815-HVC.jpg /srv/images/NOAA-18-20220603-095815-HVCT.jpg /srv/images/NOAA-18-20220603-095815-ZA.jpg /srv/images/NOAA-18-20220603-095815-therm.jpg /srv/images/NOAA-18-20220603-095815-CC.jpg /srv/images/NOAA-18-20220603-095815-HE.jpg /srv/images/NOAA-18-20220603-095815-HF.jpg /srv/images/NOAA-18-20220603-095815-MD.jpg /srv/images/NOAA-18-20220603-095815-BD.jpg /srv/images/NOAA-18-20220603-095815-MB.jpg /srv/images/NOAA-18-20220603-095815-JF.jpg /srv/images/NOAA-18-20220603-095815-JJ.jpg /srv/images/NOAA-18-20220603-095815-LC.jpg /srv/images/NOAA-18-20220603-095815-TA.jpg /srv/images/NOAA-18-20220603-095815-WV.jpg /srv/images/NOAA-18-20220603-095815-NO.jpg /srv/images/NOAA-18-20220603-095815-sea.jpg
03-06-2022 10:25 /home/pi/raspberry-noaa-v2/scripts/push_processors/push_twitter.sh INFO : Traceback (most recent call last):
  File "/home/pi/raspberry-noaa-v2/scripts/push_processors/post_to_twitter.py", line 45, in <module>
    res = api.media_upload(image)
  File "/usr/local/lib/python3.7/dist-packages/tweepy/api.py", line 3562, in media_upload
    additional_owners=additional_owners, **kwargs
  File "/usr/local/lib/python3.7/dist-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tweepy/api.py", line 3606, in simple_upload
    upload_api=True, **kwargs
  File "/usr/local/lib/python3.7/dist-packages/tweepy/api.py", line 259, in request
    raise Forbidden(resp)
tweepy.errors.Forbidden: 403 Forbidden

**Support Output**
Paste the output of running the `./support.sh` script here.
Where to find the output? The terminal close after completion.....

**Server information (please complete the following information):**
 - OS: [Rasbian 10]
 - Python version 
 - SDR device [e.g. RTL-SDR]
 - Pi3B.

**Additional context**

**Comment by meteorkees** [comment]
Solved,
you need to apply for 'elevated' access instead of 'essential' in the twitter developer portal.
