### ISSUE TITLE
error after ./install_and_upgrade.sh

### ISSUE THREAD

**Issue by rieders** [jekhokie/raspberry-noaa-v2#784]
Hello
I finally found your program.
Now I wanted to get it running on my Raspberry pi 4 4GB.
Unfortunately I get this error message after running ./install_and_upgrade.sh

* Checking configuration files...
Traceback (most recent call last):
  File "scripts/tools/validate_yaml.py", line 15, in <module>
    from jsonschema import validate, Draft7Validator
ImportError: cannot import name 'Draft7Validator' from 'jsonschema' (/usr/lib/python3/dist-packages/jsonschema/__init__.py)
Error:   Please update your config/settings.yml file to accommodate the above errors

Did I forget something in the config?

Greetings

**Comment by MihajloPi** [comment]
Hi! Try updating your RN2 version. Go to raspberry-noaa-v2 folder and run:
```bash
rm config/settings.yml
git pull
```
Then edit your new `settings.yml` file and run the install script again.

**Comment by stewrad** [comment]
I ran into the same error on a fresh install today, so another git pull only states "Already up to date". Attempted the below based on a few other things I'd seen. 
```
pip install --upgrade jsonschema

```
Unfortunately the error hasn't changed. Curious if there's a solution

**Comment by MihajloPi** [comment]
What OS versions are you running? Currently RN2 works on 32 Bullseye only. jsonschema is installed via apt, not pip, so the correct command should be:
```bash
sudo apt install python3-jsonschema
```
Can you run the support script and paste the contents here?

**Comment by stewrad** [comment]
For me, Raspberry Pi OS on a Pi 4, same as OP. 

Here's the full output when running the ./install_and_upgrade.sh

```
 * Installing yaml and jsonschema Python modules...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-jsonschema is already the newest version (2.6.0-4).
python3-yaml is already the newest version (3.13-2).
0 upgraded, 0 newly installed, 0 to remove and 603 not upgraded.
 * Checking configuration files...
Traceback (most recent call last):
  File "scripts/tools/validate_yaml.py", line 15, in <module>
    from jsonschema import validate, Draft7Validator
ImportError: cannot import name 'Draft7Validator' from 'jsonschema' (/usr/lib/python3/dist-packages/jsonschema/__init__.py)
Error:   Please update your config/settings.yml file to accommodate the above errors
```

Here's the full output from ./support.sh: 

```
=============================================
Details about environment
=============================================
Current local date/time: Tue 31 Oct 2023 07:08:54 AM HST
Current date/time (ms):  1698772134
Repo git hash:           6312b18ffccb6bc8e6d4c8d048cc8d658de9355d
Raspberry Pi Model:      Raspberry Pi 4 Model B Rev 1.1
Architecture:            Linux raspberrypi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
Num CPUs:                4
---------------------------------------------
'at' Scheduled Jobs (Captures):
./support.sh: line 36: atq: command not found
  (None)
---------------------------------------------
Satellite SDR Settings:
  meteor_m2_memory_threshold: 1000
  noaa_15_schedule: true
  noaa_15_sdr_device_id: 0
  noaa_15_freq_offset: 0
  noaa_15_enable_bias_tee: false
  noaa_15_gain: 29.7
  noaa_15_sun_min_elevation: 6
  noaa_15_sat_min_elevation: 30
  noaa_18_schedule: true
  noaa_18_sdr_device_id: 0
  noaa_18_freq_offset: 0
  noaa_18_enable_bias_tee: false
  noaa_18_gain: 29.7
  noaa_18_sun_min_elevation: 6
  noaa_18_sat_min_elevation: 30
  noaa_19_schedule: true
  noaa_19_sdr_device_id: 0
  noaa_19_freq_offset: 0
  noaa_19_enable_bias_tee: false
  noaa_19_gain: 29.7
  noaa_19_sun_min_elevation: 6
  noaa_19_sat_min_elevation: 30
  meteor_m2_3_schedule: true
  meteor_m2_3_sdr_device_id: 0
  meteor_m2_3_freq_offset: 0
  meteor_m2_3_enable_bias_tee: false
  meteor_m2_3_gain: 29.7
  meteor_m2_3_schedule_sun_min_elevation: -90
  meteor_m2_3_sun_min_elevation: 6
  meteor_m2_3_sat_min_elevation: 30
  meteor_m2_3_80k_interleaving: false
---------------------------------------------
USB Device Map:
  Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
  Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
  Bus 001 Device 003: ID 1c4f:0063 SiGma Micro 
  Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
  Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
---------------------------------------------
Disk Info:
  NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
  mmcblk0     179:0    0 14.9G  0 disk 
  ├─mmcblk0p1 179:1    0  2.4G  0 part 
  ├─mmcblk0p2 179:2    0    1K  0 part 
  ├─mmcblk0p5 179:5    0   32M  0 part 
  ├─mmcblk0p6 179:6    0  256M  0 part /boot
  └─mmcblk0p7 179:7    0 12.2G  0 part /
---------------------------------------------
Disk Usage Info:
  Filesystem     1K-blocks     Used Available Use% Mounted on
  /dev/root       12420920 11295400    471520  96% /
  devtmpfs         1867796        0   1867796   0% /dev
  tmpfs            1999892        0   1999892   0% /dev/shm
  tmpfs            1999892     8772   1991120   1% /run
  tmpfs               5120        4      5116   1% /run/lock
  tmpfs            1999892        0   1999892   0% /sys/fs/cgroup
  /dev/mmcblk0p6    258094    53033    205062  21% /boot
  tmpfs             399976        0    399976   0% /run/user/1000
---------------------------------------------
Memory Info:
  MemTotal:        3999784 kB
  MemFree:         1617084 kB
  MemAvailable:    3609360 kB
---------------------------------------------
Git source files changed:
  (None)
---------------------------------------------
SDR Information:
No supported devices found.
---------------------------------------------
Database tables:
  (None)
```

**Comment by MihajloPi** [comment]
@stewrad when did you last update/download RN2? I see some problems with jsonschema Python package and at not being installed via apt...

**Comment by stewrad** [comment]
The original git clone is from 2 days ago, and the error popped up on my first time running the install

**Comment by rieders** [comment]
Hello
I'm using Raspberry Pi's Buster OS.
I would like to keep an existing system running.
I have already tried to update the system to Bullseye and although I can install NOAA V2, my previous application no longer starts.

**Comment by MihajloPi** [comment]
> Hello
> I'm using Raspberry Pi's Buster OS.
> I would like to keep an existing system running.
> I have already tried to update the system to Bullseye and although I can install NOAA V2, my previous application no longer starts.

New features haven't been tested on Buster as it's older than Bullseye, so I'm not sure if it will still work on it, especially the SatDump. It is recommended to reflash a fresh Bullseye OS instead of updating Buster to Bullseye.

**Comment by rieders** [comment]
Good day
Many thanks for the quick response.
I have already installed satdump version V1.1.1 on the current Bullseye system. Is it possible to reinstall Radiosondy manually?
I would be happy if it is somehow possible.

Greetings

**Comment by rieders** [comment]
How can I transfer or install the Radiosondy system to a Bullseye system?

Greetings

**Comment by ybennouna** [comment]
The script jsonschema is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH
